-- Transactions Table
CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    TRANSACTION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ACTION_TMSP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SYMBOL VARCHAR(10),
    TYPE VARCHAR(4),
    PRICE DECIMAL(8,4),
    QUANTITY DECIMAL(8,4)
);

-- User Information Table
CREATE TABLE IF NOT EXISTS USER_INFO (
    USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FIRST_NAME VARCHAR(25) DEFAULT NULL,
    LAST_NAME VARCHAR(25) DEFAULT NULL,
    USER_NAME VARCHAR(25) NOT NULL,
    CREATION_TMSP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- User Transaction Table
CREATE TABLE IF NOT EXISTS USER_TRANSACTIONS (
    TRANSACTION_ID INTEGER NOT NULL,
    USER_ID INT NOT NULL,
    LOT DECIMAL(7,4),
    STATUS VARCHAR(6),
    PROFIT DECIMAL(15,8),
    CREATION_TMSP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATE_TMSP TIMESTAMP,
    PRIMARY KEY (TRANSACTION_ID, USER_ID),
    FOREIGN KEY (USER_ID)
        REFERENCES USER_INFO (USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (TRANSACTION_ID)
        REFERENCES TRANSACTIONS (TRANSACTION_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USER_DEPOSITS (
    USER_ID INT NOT NULL,
    DEPOSIT DECIMAL(15,8) DEFAULT 0,
    WITHDRAWAL DECIMAL(15,8) DEFAULT 0,
    FOREIGN KEY (USER_ID)
        REFERENCES USER_INFO (USER_ID) ON DELETE CASCADE
);

-- Inserts
INSERT INTO USER_INFO (FIRST_NAME, LAST_NAME, USER_NAME) VALUES ('Maxime', 'Sirois', 'SIRMAX');